stages:
  training:
    cmd: "C:/Users/Roman/AppData/Local/Programs/Python/Python310/python.exe A:/educ/FoxesNN/main.py --epochs 10"
    deps:
      - main.py
      - tree_ds.csv
    outs:
      - best_fish_classifier.pth